name: busy_buttons
description: "A new Flutter package project."
version: 0.0.1
homepage: https://github.com/plokmij/busy_buttons

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter: